spring:
  application:
    name: ${CONFIG_SERVER_NAME}
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations/

server:
  port: 8888
